/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zyh_ndktest_Ndk */

#ifndef _Included_com_example_zyh_ndktest_Ndk
#define _Included_com_example_zyh_ndktest_Ndk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zyh_ndktest_Ndk
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zyh_ndktest_Ndk_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
